project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from web import urls as web_urls
from mobi import urls as mobi_urls

urlpatterns = [
    url(r'^nimda/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^', include(web_urls)),
    url(r'^', include(mobi_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import include, url

urlpatterns = [

    # ajax urls
    url(r'^accept_request/$', 'web.views.accept_request'),
    url(r'^request_friendship/$', 'web.views.request_friendship'),
    url(r'^reject_request/$', 'web.views.reject_request'),
    url(r'^delete_friendship/$', 'web.views.delete_friendship'),
    url(r'^can_come/$', 'web.views.can_come'),
    url(r'^cannot_come/$', 'web.views.cannot_come'),
    url(r'^cancel_decision/$', 'web.views.cancel_decision'),
    url(r'^cancel_request/$', 'web.views.cancel_request'),
    url(r'^request_membership_in_group/$', 'web.views.request_membership_in_group'),
    url(r'^cancel_request_membership_in_group/$', 'web.views.cancel_request_membership_in_group'),
    url(r'^user_accepts_invitation/$', 'web.views.user_accepts_invitation'),
    url(r'^group_approves_request/$', 'web.views.group_approves_request'),
    url(r'^reject_invitation_from_group/$', 'web.views.reject_invitation_from_group'),
    url(r'^leave_group/$', 'web.views.leave_group'),
    url(r'^clear_notification/$', 'web.views.clear_notification'),
    url(r'^ajax/friends/$', 'web.views.ajax_friends'),
    url(r'^ajax/facebook_friends/$', 'web.views.ajax_facebook_friends'),
    url(r'^invite_friend_to_group/$', 'web.views.invite_friend_to_group'),
    url(r'^share_event/$', 'web.views.share_event'),
    url(r'^subscribe/(?P<pk>\d+)/$', 'web.views.subscribe', name='subscribe'),
    url(r'^subscribe_group/(?P<pk>\d+)/$', 'web.views.subscribe_group', name='subscribe_group'),
    url(r'^add_friend_to_friend_list/$', 'web.views.add_friend_to_friend_list'),
    url(r'^add_contact_to_friend_list/$', 'web.views.add_contact_to_friend_list'),
    url(r'^invite_friend_to_event/$', 'web.views.invite_friend_to_event'),
    url(r'^invite_friend_list_to_event/$', 'web.views.invite_friend_list_to_event'),
    url(r'^mark_non_new_user/$', 'web.views.mark_non_new_user'),
    url(r'^search_invite_event_json/(?P<pk>\d+)/$', 'web.views.search_invite_event_json'),
    url(r'^search_invite_group_json/(?P<pk>\d+)/$', 'web.views.search_invite_group_json'),
    url(r'^create_contact_and_add_to_list/(?P<pk>\d+)/$', 'web.views.create_contact_and_add_to_list'),
    url(r'^more_events/$', 'web.views.more_events'),

    # event urls
    url(r'^events/(?P<pk>\d+)/$', 'web.views.event_detail_view', name='event_detail_view'),
    url(r'^home/$', 'web.views.event_list_view', name='event_list_view'),
    url(r'^today/$', 'web.views.today_events_view', name='today_events_view'),
    url(r'^events/delete/(?P<pk>\d+)/$', 'web.views.event_delete_view', name='event_delete_view'),
    url(r'^events/update/(?P<pk>\d+)/$', 'web.views.event_update_view', name='event_update_view'),
    url(r'^events/create/$', 'web.views.event_create_view', name='event_create_view'),
    url(r'^invite_friends_to_event/(?P<pk>\d+)/$', 'web.views.invite_friends_to_event_view', name='invite_friends_to_event_view'),
    url(r'^invite_friend_lists_to_event/(?P<pk>\d+)/$', 'web.views.invite_friend_lists_to_event_view', name='invite_friend_lists_to_event_view'),
    url(r'^share_buttons/(?P<pk>\d+)/$', 'web.views.share_buttons', name='share_buttons'),
    url(r'^calendar_buttons/(?P<pk>\d+)/$', 'web.views.calendar_buttons', name='calendar_buttons'),
    # url(r'^search/events/$', 'web.views.search_events', name='search_events'),


    # group urls    
    url(r'^groups/$', 'web.views.group_list_view', name='group_list_view'),
    url(r'^groups/(?P<pk>\d+)/$', 'web.views.group_event_list', name='group_event_list'),
    url(r'^groups/(?P<pk>\d+)/members/$', 'web.views.group_member_view', name='group_member_view'),
    url(r'^groups/(?P<pk>\d+)/delete/$', 'web.views.group_delete_view', name='group_delete_view'),
    url(r'^groups/(?P<pk>\d+)/update/$', 'web.views.group_update_view', name='group_update_view'),
    url(r'^groups/create/$', 'web.views.group_create_view', name='group_create_view'),
    url(r'^groups/search/$', 'web.views.search_groups', name='search_groups'),
    # url(r'^search/groups/$', 'web.views.search_groups', name='search_groups'),


    # friendlist urls
    url(r'^friends/list/(?P<pk>\d+)/$', 'web.views.friend_list_detail_view', name='friend_list_detail_view'),
    url(r'^friend/list/(?P<pk>\d+)/delete/$', 'web.views.friend_list_delete_view', name='friend_list_delete_view'),
    url(r'^pick_friends_for_list/(?P<pk>\d+)/$', 'web.views.pick_friends_for_list', name='pick_friends_for_list'),



    # userprofile urls
    url(r'^people/(?P<pk>\d+)/$', 'web.views.profile_detail_view', name='profile_detail_view'),
    url(r'^friends/$', 'web.views.friend_list', name='friend_list'),
    url(r'^friends/(?P<pk>\d+)/$', 'web.views.other_friend_list', name='other_friend_list'),
    url(r'^friends/(?P<pk>\d+)/mutual/$', 'web.views.other_mutual_list', name='other_mutual_list'),
    url(r'^search/profiles/$', 'web.views.search_profiles', name='search_profiles'),
    url(r'^profile/(?P<pk>\d+)/update/$', 'web.views.profile_update_view', name='profile_update_view'),
    url(r'^profile/create/$', 'web.views.profile_create_view', name='profile_create_view'),
    url(r'^notifications/$', 'web.views.full_notifications', name='full_notifications'),
    url(r'^signup/$', 'web.views.signup', name='signup_view'),
    url(r'^login_view/$', 'web.views.login_view', name='login_view'),

    # permission urls
    url(r'^logout_view/$', 'web.views.logout_view', name='logout_view'),
    url(r'^$', 'web.views.new_user', name='new_user'),
    url(r'^about/$', 'web.views.about_view', name='about_view'),
    url(r'^contact/$', 'web.views.contact_view', name='contact_view'),
    url(r'^thank-you/$', 'web.views.thank_you', name='thank_you'),

    # comment urls
    url(r'^delete/comment/(?P<pk>\d+)/$', 'web.views.comment_delete_view', name='comment_delete_view')

    
]

main/forms.py
import datetime
from location_picker import LocationPickerWidget

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm, UserChangeForm

from .models import Event, Group, Profile, FriendList

#Event forms

valid_time_formats = ['%I:%M %p', '%P', '%H:%M%A', '%H:%M %A', '%H:%M%a', '%H:%M %a']


class BasicEventCreate(forms.Form):
    summary = forms.CharField()
    date_happening = forms.DateField(initial=datetime.datetime.now())
    time_starting = forms.TimeField(input_formats=valid_time_formats)
    location = forms.CharField()
    test_location = forms.CharField()



class EventModelCreateForm(forms.ModelForm):
    date_happening = forms.DateField(initial=datetime.datetime.now())
    time_starting = forms.TimeField(input_formats=valid_time_formats)
    time_ending = forms.TimeField(input_formats=valid_time_formats)




    class Meta:
        model = Event
        exclude = ['date_posted', 'people_coming', 'people_not_coming']

    def __init__(self, *args, **kwargs):
        super(EventModelCreateForm, self).__init__(*args, **kwargs)
        self.fields["host"].widget = forms.CheckboxSelectMultiple()
        self.fields["groups"].widget = forms.CheckboxSelectMultiple()
        self.fields["test_location"].widget = LocationPickerWidget()
        self.fields["location"].required = True
        self.fields["name"].required = True
        self.fields["date_happening"].required = True
        self.fields["time_starting"].required = True
        self.fields["time_ending"].required = True
        self.fields["description"].required = False
        self.fields["description"].widget = forms.Textarea(attrs={'rows': '4'})


class EventModelUpdateForm(forms.ModelForm):  

    date_happening = forms.DateField()
    time_starting = forms.TimeField(input_formats=valid_time_formats)
    time_ending = forms.TimeField(input_formats=valid_time_formats)

    class Meta:
        model = Event
        exclude = ['date_posted', 'people_coming', 'people_not_coming']

    def __init__(self, *args, **kwargs):
        super(EventModelUpdateForm, self).__init__(*args, **kwargs)
        self.fields["host"].widget = forms.CheckboxSelectMultiple()
        self.fields["groups"].widget = forms.CheckboxSelectMultiple()
        self.fields["test_location"].widget = LocationPickerWidget()
        self.fields["location"].required = True
        self.fields["name"].required = True
        self.fields["date_happening"].required = True
        self.fields["time_starting"].required = True
        self.fields["time_ending"].required = True
        self.fields["description"].required = False
        self.fields["description"].widget = forms.Textarea(attrs={'rows': '4'})




#Group forms
class GroupModelCreateForm(forms.ModelForm):  
    class Meta:
        model = Group
        exclude = ['members', 'member_requests']

    def __init__(self, *args, **kwargs):
        super(GroupModelCreateForm, self).__init__(*args, **kwargs)
        self.fields["admin"].widget = forms.CheckboxSelectMultiple()        
        self.fields["name"].required = True
        self.fields["description"].required = True
        self.fields["description"].widget = forms.Textarea(attrs={'rows': '4'})



class GroupModelUpdateForm(forms.ModelForm):  
    class Meta:
        model = Group
        exclude = ['member_requests', 'admin']

    def __init__(self, *args, **kwargs):
        super(GroupModelUpdateForm, self).__init__(*args, **kwargs)
        self.fields["members"].widget = forms.CheckboxSelectMultiple()       
        self.fields["name"].required = True
        self.fields["description"].required = True
        self.fields["description"].widget = forms.Textarea(attrs={'rows': '4'})



#Profile / User forms
class SearchProfile(forms.Form):
    search = forms.CharField(required=False, widget=forms.TextInput(attrs={'id': 'search', 'placeholder': 'Search for friends!', 'class': 'form-control'}))


class UserLogin(forms.Form):  
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, widget=forms.PasswordInput())


class UserModelCreateForm(UserCreationForm):  
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        new_user = super(UserCreateForm, self).save(commit=False)
        new_user.email = self.cleaned_data["email"]
        new_profile = Profile.objects.create(user=new_user)
        new_profile.save()
        if commit:
            new_user.save()
        return user


class UserModelUpdateForm(UserChangeForm):  
    class Meta:
        model = User
        exclude = ['name']


class ProfileModelCreateForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())
    verification = forms.CharField(widget=forms.TextInput(attrs={'placeholder': "What is 2+4?"}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'rows': '5'}))
    class Meta:
        model = Profile
        exclude = ['user', 'new_user', 'friends', 'events_posted', 'shared_events', 'group_requests', 'friend_requests', 'past_events', 'followers']


class ProfileModelUpdateForm(forms.ModelForm):  
    class Meta:
        model = Profile
        exclude = ['user', 'past_events', 'friends', 'friend_requests', 'events_posted', 'shared_events', 'group_requests', 'followers']


class ContactForm(forms.Form):
    author = forms.CharField(required=True, widget=forms.TextInput(attrs={'id': 'author', 'placeholder': 'Your name *', 'class': 'form-control'}))
    comment = forms.CharField(required=True, widget=forms.Textarea(attrs={'id': 'comment', 'placeholder': 'Your message *', 'class': 'form-control', 'rows': '4'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'id': 'email', 'placeholder': 'Your email *', 'class': 'form-control'}))


class CommentForm(forms.Form):
    message = forms.CharField(required=False, label="Enter your comment here!", widget=forms.Textarea(attrs={'id': 'comment_body', 'class': "form-control", 'placeholder':"Why I oughta..."}))


class FriendListCreate(forms.Form):
    name = forms.CharField(required=False, label="Enter the name of your new Friend List here!", widget=forms.TextInput(attrs={'id': 'comment_body', 'class': "form-control", 'placeholder':"Type the name here"}))


class ContactCreate(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'id': 'name-input', 'class': "form-control", 'placeholder':"Who is it?", 'style': 'width: 80%'}))
    contact_method = forms.CharField(widget=forms.TextInput(attrs={'id': 'method-input', 'class': "form-control", 'placeholder':"Email or phone #", 'style': 'width: 80%'}))

web/templates/calendar_buttons.html
<a class="btn btn-danger" target="_blank" href='{{google_cal}}'><i class='fa fa-google'></i>&nbsp;&nbsp;CALENDAR</a>
<br>
<a style="margin-top: 10px" class="btn btn-info" target="_blank" href='{{apple_cal}}'><i class='fa fa-apple'></i>&nbsp;&nbsp;CALENDAR</a>

web/templates/event_update.html
{% extends 'base.html' %}
{% load addcss %}
{% load staticfiles %}

{% block title %}Edit "{{ event.name }}"{% endblock title %}


{% block body %}
<div class="container">
    <form action="{% url 'event_update_view' event.pk %}" enctype="multipart/form-data" method='POST'  id='update-form'>
    <div class="row">
        <h2>EDIT <i>"{{ event.name|upper }}"</i></h2>    
        {% if saved %}<p class="green" id="saved">{{ saved }}</p>{% endif %} 
        {% csrf_token %}    
            <div class="col-md-5 col-md-offset-1">
                    Name: {{ form.name|addcss:"form-control" }}
                    <span class='red' id='name-errors'></span>
                    <hr>
                    <i class="fa fa-calendar-o"></i>
                    Date: {{form.date_happening|addcss:"form-control datepicker"}}
                    <i class="fa fa-clock-o"></i>
                    Time Starting: {{form.time_starting|addcss:"form-control timepicker"}}
                    <span class='red' id='start-time-errors'></span>
                    <i class="fa fa-clock-o"></i>
                    Time Ending: {{form.time_ending|addcss:"form-control timepicker"}}
                    <span class='red' id='end-time-errors'></span>
                    <hr>
                    <i class="fa fa-map-marker"></i>
                    Location: {{ form.location|addcss:"form-control" }}
                    <span class='red' id='location-errors'></span>
                    {{ form.test_location|addcss:"form-control"}}
                    <input name="event_pk" class="hidden" value="{{ event_pk }}">
                    <span id="update" class="hidden">update</span>
            </div>
            <div class="col-md-4 col-md-offset-1">
                Description: {{ form.description|addcss:"form-control" }}
                <span class='red' id='description-errors'></span>
                <hr style="margin-bottom: 5px; margin-top: 10px;">
                <strong class="bigger">Allow sharing?</strong>{{ form.shareable }}<br style="margin-top: 100px">
                Allow others to repost this event and invite their friends<br><br>
                <strong class="bigger">Make Public?</strong>{{ form.public }}<br>
                Post this event to all your friends' event feeds.<br>If an event is not public, you should invite people or tag a specific Group Feed!
                
                <!--Host: <small>(besides yourself, of course)</small><div class="overflow form-control">{{form.host}}
                </div>-->
                <hr style="margin-bottom: 5px; margin-top: 10px;">
                <br><br>
                <strong>Group Feeds</strong><br>
                <div class="overflow form-control">{{form.groups}}
                </div>
            </div>
        </div>
        {% if errors %}
            <div class="red text-center errors">Uh oh! {{ errors|safe }}</div>   
        {% else %}
            <br>
        {% endif %}
        <div class="row">
            <div class="col-md-4 col-md-offset-2">
                <input class="form-control btn-default submit" type="submit" value="SAVE AND FINISH" id="_finish" />
            </div>
            <div class="col-md-4 ">
                <input class="form-control btn-default submit" type="submit" value="SAVE AND CONTINUE EDITING" id="_continue"/>            
            </div>
        </div>
        <input id="current-timezone" name="timezone" class="hidden" value="UTC">
        <input id="finish" name="_finish" class="hidden">
        </form>
        <br>
    </div>
</div>
{% endblock %}

{% block links %}
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/jquery.timeentry.css' %}">
    <link rel="stylesheet" href="{% static 'location_picker/location_picker.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
    
{% endblock links %}

{% block scripts %}
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?libraries=places"></script>
    <script type="text/javascript" src="{% static 'js/jstz-1.0.4.min.js' %}"></script>
    
    <script src="{% static 'js/jquery.plugin.min.js' %}"></script>
    <script src="{% static 'js/jquery.timeentry.min.js' %}"></script>
    
    <script src="{% static 'js/jquery.popup.min.js' %}"></script>
    <script src="{% static 'js/switch-boxes.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/switch-boxes.css' %}">
    <script type="text/javascript">
        $(document).ready(function() {
          $(':checkbox').iphoneStyle({
              checkedLabel: 'YES',
              uncheckedLabel: 'NO'
            });
        });
  </script>
  <script type="text/javascript">
      $('.submit').on('click', function(e) {
            e.preventDefault();
            if (checkForErrors()) {
                if (e.target.id == '_finish') {
                    $('#finish').val("_finish");
                }
                $('#update-form').submit()
            };
      });

        function checkForErrors() {
            var now = new Date()
            console.log(now)
            console.log(date)
            var from = $(".datepicker").val().split("-");

            var date = new Date(from[0], from[1] - 1, from[2]);
            var dateString = date.toDateString().split(" 00")[0] + " "
            var start = new Date(dateString + $('#id_time_starting').val())
            var end = new Date(dateString + $('#id_time_ending').val())

            var timeComp = new Date("1 Jan 2000 " + now.toTimeString())
            var lateDate = new Date("1 Jan 2000 9:30 PM")
            var earlyDate = new Date("2 Jan 2000 5:00 AM")
            

            var startComp = new Date("1 Jan 2000 " + $('#id_time_starting').val())
            var endComp = new Date("2 Jan 2000 " + $('#id_time_ending').val())

            var shouldSubmit = true
            if (end > start || (startComp > lateDate && endComp < earlyDate)) {
                $('#id_time_ending').css('border', '1px solid #cccccc');
                $('#end-time-errors').text('');
            } else {
                $('#id_time_ending').css('border', '1px solid red');
                $('#end-time-errors').text('The end time cannot be before the start time.')
                shouldSubmit = false;
            };
            if (startComp > timeComp ) { 
                $('#id_time_starting').css('border', '1px solid #cccccc');
                $('#id_date_happening').css('border', '1px solid #cccccc');
                $('#start-time-errors').html('')
            } else {
                $('#id_time_starting').css('border', '1px solid red');
                $('#id_date_happening').css('border', '1px solid red');
                $('#start-time-errors').html('The start time cannot be in the past.<br>')
                shouldSubmit = false;
            }
            if ($('#id_name').val()) { 
                $('#id_name').css('border', '1px solid #cccccc');
                $('#name-errors').text('')
            } else {
                $('#id_name').css('border', '1px solid red');
                $('#name-errors').text('An event name is required!')
                shouldSubmit = false;
            }
            if ($('#id_location').val()) {
                $('#id_location').css('border', '1px solid #cccccc');
                $('#location-errors').text('')
            } else {
                $('#id_location').css('border', '1px solid red');
                $('#location-errors').text('An event location is required!')
                shouldSubmit = false;
            }


            return shouldSubmit;
        }
  </script>
{% endblock scripts %}

web/templates/facebook_friends.html
{% load thumbnail %}

<h3>Your Facebook Friends on WAYD</h3>
<div id="friends">
{% if friends.exists %}
    {% for friend in friends %}
        <div class="event-detail" style="border-bottom: 1px solid #EEE; min-height: 40px;">
            {% thumbnail  friend.picture "200x200" crop="center" as im %}
                <img src="{{ im.url }}" class="port-item" width="60" height="60" style="border-radius: 30px;" alt="{{ person }}">
            {% endthumbnail %}
            <a href="{% url 'profile_detail_view' friend.pk %}" >{{ friend }}</a>
            <strong id='div-invite-friend-{{friend.pk}}'>&nbsp;
            {% if friend in request.user.profile.friend_requests.all %}     
                <a id='reject-friend-{{friend.pk}}' class="btn btn-sm btn-danger reject-friend" style="float: right; margin-top: 12px;" href="#invite-to-group" alt='{{friend.pk}}'>REJECT</a>     
                <a id='accept-friend-{{friend.pk}}' class="btn btn-sm btn-success accept-friend" style="float: right; margin-top: 12px;" href="#invite-to-group" alt='{{friend.pk}}'>ACCEPT</a>&nbsp;  
            {% elif request.user.profile not in friend.friend_requests.all %} 
                <a id='invite-friend-{{friend.pk}}' class="btn btn-sm btn-success add-friend" style="float: right; margin-top: 12px;" href="#invite-to-group" alt='{{friend.pk}}'>ADD</a>
            {% else %}
                <h5 style="float: right; margin-top: 20px;" class="green">ADDED</h5>
            {% endif %}
            </strong>
        </div>
    {% endfor %}
{% else %}
    <h5>You have no friends to add!</h5>
{% endif %}
</div>

<script type="text/javascript">
$('#friends').on('click', '.add-friend', function(e) {
    e.preventDefault();
    console.log('user adding facebook friend');
    console.log('#'+e.target.id)
    var person_pk = $('#'+e.target.id).attr('alt');
    $.ajax({
        type: 'GET',
        url: '/request_friendship/',
        data: {
            pk: person_pk,
        },
        success: function(data) {
            $("#div-invite-friend-"+person_pk).html('');
            $("#div-invite-friend-"+person_pk).html('<h5 style="float: right; margin-top: 20px;" class="green">Added!</h5>');
        }
    });
});

$('#friends').on('click', '.accept-friend', function(e) {
    e.preventDefault();
    console.log('user adding facebook friend');
    console.log('#'+e.target.id)
    var person_pk = $('#'+e.target.id).attr('alt');
    $.ajax({
        type: 'GET',
        url: '/accept_request/',
        data: {
            pk: person_pk,
        },
        success: function(data) {
            $("#div-invite-friend-"+person_pk).html('');
            $("#div-invite-friend-"+person_pk).html('<h5 style="float: right; margin-top: 20px;" class="green">ACCEPTED!</h5>');
        }
    });
});

$('#friends').on('click', '.reject-friend', function(e) {
    e.preventDefault();
    console.log('user adding facebook friend');
    console.log('#'+e.target.id)
    var person_pk = $('#'+e.target.id).attr('alt');
    $.ajax({
        type: 'GET',
        url: '/reject_request/',
        data: {
            pk: person_pk,
        },
        success: function(data) {
            $("#div-invite-friend-"+person_pk).html('');
            $("#div-invite-friend-"+person_pk).html('<h5 style="float: right;" class="red">REJECTED...</h5>');
        }
    });
});
</script>

web/templates/group_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load addcss %}

{% block title %}Create a new Group Feed{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>CREATE A NEW GROUP FEED</h2>
            <form action="{% url 'group_create_view' %}" enctype="multipart/form-data" method="POST" >
                {% csrf_token %}    
                Name:
                {{ form.name|addcss:"form-control" }}
                Description
                {{ form.description|addcss:"form-control" }}
                Admins of your new Group Feed! <small>(besides yourself, of course)</small>:
                <div class="overflow form-control">{{ form.admin }}</div>
                <br>

                <strong class="bigger">Allow searching?</strong>{{ form.searchable }}<br style="margin-top: 100px">
                Allow others to find this Group Feed via searching<br><br>
                <strong class="bigger">Make Open?</strong>{{ form.open_group }}<br>
                Allow new members to join without being approved<br><br>
                <strong class="bigger">Only Admins Can Post?</strong>{{ form.admin_only }}<br>
                Ensure only Group Feed Admins can post events.<br>If you're making a Group Feed for an organization, leave this yes!
                <br>
                <div class="red text-center"><p>{{ errors }}</p></div>    
                <input class="form-control" type="submit" value="CREATE GROUP FEED" />
            </form>
        </div>
    </div>
    <br>
</div>

{% endblock %}


{% block scripts %}
    <script src="{% static 'js/switch-boxes.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/switch-boxes.css' %}">
    <script type="text/javascript">
        $(document).ready(function() {
          $(':checkbox').iphoneStyle({
              checkedLabel: 'YES',
              uncheckedLabel: 'NO'
            });
        });
  </script>
{% endblock scripts %}

web/templates/group_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load addcss %}

{% block title %}Edit "{{ group.name}}"{% endblock title %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h2>EDIT "{{ group.name|upper}}"</h2>
            <form action="{% url 'group_update_view' group.pk %}" enctype="multipart/form-data" method="POST" >
                {% csrf_token %}    
                Name:
                {{ form.name|addcss:"form-control" }}
                Description
                {{ form.description|addcss:"form-control" }}
                Members of your new Group Feed! <small>(uncheck to kick from the Group)</small>:
                <div class="overflow form-control">{{ form.members }}</div>
                <br>

                <strong class="bigger">Allow searching?</strong>{{ form.searchable }}<br style="margin-top: 100px">
                Allow others to find this Group Feed via searching<br><br>
                <strong class="bigger">Make Open?</strong>{{ form.open_group }}<br>
                Allow new members to join without being approved<br><br>
                <strong class="bigger">Only Admins Can Post?</strong>{{ form.admin_only }}<br>
                Ensure only Group Feed Admins can post events.<br>If you're making a Group Feed for an organization, keep this yes!
                <br>
                <div class="red text-center"><p>{{ errors }}</p></div>    
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-2">
            <input class="form-control btn-default" type="submit" value="SAVE AND FINISH" name="_finish" />
        </div>
        <div class="col-md-4 ">
            <input class="form-control btn-default" type="submit" value="SAVE AND CONTINUE EDITING" name="_continue"/>            
        </div>
    </div>
    </form>
    <br>
</div>

{% endblock %}


{% block scripts %}
    <script src="{% static 'js/switch-boxes.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/switch-boxes.css' %}">
    <script type="text/javascript">
        $(document).ready(function() {
          $(':checkbox').iphoneStyle({
              checkedLabel: 'YES',
              uncheckedLabel: 'NO'
            });
        });
  </script>
{% endblock scripts %}